name: Zihin Kutusu Android Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi indir
        uses: actions/checkout@v4

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Android Command Line Tools indir
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd /tmp
          curl -L -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-15859902_latest.zip
          unzip -q commandlinetools.zip
          mkdir -p "$ANDROID_HOME/cmdline-tools/latest"
          cp -r cmdline-tools/* "$ANDROID_HOME/cmdline-tools/latest/"

      - name: Android SDK paketlerini kur
        run: |
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"

      - name: Gradle kurulumu
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: AAB oluştur
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew :app:bundleRelease
      - name: APK oluştur
        run: |
          gradle :app:assembleDebug

      - name: AAB dosyasını yükle
        uses: actions/upload-artifact@v4
        with:
          name: ZihinKutusu-AAB
          path: app/build/outputs/bundle/release/*.aab

      - name: APK dosyasını yükle
        uses: actions/upload-artifact@v4
        with:
          name: ZihinKutusu-APK
          path: app/build/outputs/apk/debug/*.apk
